### ISSUE TITLE
Does not identify matches

### ISSUE THREAD

**Issue by Anexis19** [forgetso/search-replace#103]
First of all, thank you for your extension, you can't imagine how much work you have saved me. In this new version, it fails to identify matches found in text fields of a form.  I have already used the extension on this site and it worked perfectly. 

![image](https://github.com/forgetso/search-replace/assets/71296480/7be2947c-e5b3-4ae3-bb89-77b76b4471f4)

Regards

**Comment by forgetso** [comment]
Thanks @Anexis19 for the detailed information. I will look into this issue for research-opinions.com and provide you with an update soon.

**Comment by forgetso** [comment]
Hi @Anexis19 I can't login to this site. I can only create an account on LimeSurvey. If you could download the full page with this tool (https://chromewebstore.google.com/detail/singlefile/mpiodijhokgodhhofbcjdecpffjipkle?hl=en) and attach it to this ticket then I will be able to diagnose the issue. Thanks.

**Comment by Anexis19** [comment]
Hi Chris, thanks for your fast response

Here is the page where I usually use the extension

Thank you so much

**Comment by forgetso** [comment]
Hi @Anexis19, I think you might need to attach the attachment from inside GitHub. There is nothing attached to your last post.

Please also check out version [2.0.5](https://github.com/forgetso/search-replace/releases/tag/2.0.5), which will be released soon. It has a fix for counts not happening when other chrome extensions have injected iframes into the page. Are you using additional chrome extensions by any chance?

You can preview 2.0.5 by [loading an unpacked extension in Chrome](https://superuser.com/a/247654/174115). You would need to load the folder called `dist` inside the release.

Thanks,

Chris

**Comment by Anexis19** [comment]
Sorry, my bad. I currently use these extensions 

![image](https://github.com/forgetso/search-replace/assets/71296480/a84fa9d1-4949-4144-a781-7066ee8155b9)
[search_and_replace_2.0.5.zip](https://github.com/forgetso/search-replace/files/14055541/search_and_replace_2.0.5.zip)

Regards
Andres

**Comment by forgetso** [comment]
Hey Andres,

Thanks for checking out the new version. I think you've maybe attached the wrong file - you attached version 2.0.5 of my extension. In order to debug, I need you carry out the following steps:

1. install https://chromewebstore.google.com/detail/singlefile/mpiodijhokgodhhofbcjdecpffjipkle?hl=en
2. go to the page with the issue (research-opinions.com)
3. Click the singlefile extension in the chrome tool bar - it will download a .zip of the page
4. Attach the .zip of the page here and I can use it for testing

Thanks!

**Comment by Anexis19** [comment]
Hi Chris

God! my bad again, really really sorry

[Research-Opinions.zip](https://github.com/forgetso/search-replace/files/14056045/Research-Opinions.zip)

Really Thanks for all you patience

**Comment by forgetso** [comment]
Hi @Anexis19, I've tried this locally with 2.0.5 and it seems to be working. See this video: https://i.imgur.com/EoMTp4u.gif

Here's a version with debugging enabled. Perhaps you could try this, [check the developer console](https://developer.chrome.com/docs/devtools/open/), and paste any errors that it outputs.

[search_and_replace_2.0.5-dev.zip](https://github.com/forgetso/search-replace/files/14057425/search_and_replace_2.0.5-dev.zip)

Then I might know what's going on with your version.

Thanks!

**Comment by forgetso** [comment]
Hi @Anexis19, any luck trying the debug version? I'd be interested to hear if you're still having the problem as I would really like to get it fixed. I'm available for a call during weekdays if you'd be willing to help. Thanks

See [this link] for details on how to enable the old version in the meantime.

**Comment by Anexis19** [comment]
Hi Chris.

Sorry for the late reply. I don't resolve the issue. It's weird because
other friend use the extension and they don't have any problem with it.
There's any option to have a call today?

Regards

**Comment by forgetso** [comment]
Hi @Anexis19, I can't do this weekend. Is there a time on Monday that suits you? I can do 1000-1600 GMT.

**Comment by forgetso** [comment]
It would also be helpful if you could provide additional information in the meantime:

- Browser Version (e.g. Version 1.58.127 Chromium: 117.0.5938.88 (Official Build) (64-bit))
- Operating System (e.g. Windows 11, Windows 10, Mac OSX ...)

Thanks!

**Comment by rosasparks420** [comment]
I don't wanna bother you with a new thread about an issue you're aware of so tucking this in here.

Search and Replace Version 2.0.6
Windows 10, Chrome Version 120.0.6099.225 (Official Build) (64-bit) - updating though as I type this to Version 121.0.6167.86 (Official Build) (64-bit) and the update didn't help it work.
![image](https://github.com/forgetso/search-replace/assets/106178465/97ff0ed5-8716-416a-8dd1-b2c6ee38d07e)

ALSO

Search and Replace Version 2.0.6
Mac OS 10.15.7, Chrome Version 120.0.6099.234 (Official Build) (x86_64) - updating while typing again to Version 121.0.6167.85 (Official Build) (x86_64) Chrome update did nothing on the Mac either.
![image](https://github.com/forgetso/search-replace/assets/106178465/7aff212a-d56a-48db-baa4-b66999e422f6) (sorry bout that retina resolution)

Webpage I'm having issues on is webflow.com, in the designer / editor specifically the ecom section.

Options checked are input fields only, match whole word - tried without options for curiosity sake, still not working.

*Extension works perfect on the website I'm designing (can provide link if you wish), with all of the same options checked on both PC and Mac.* PC seen here
![image](https://github.com/forgetso/search-replace/assets/106178465/7d2a4e4a-5d98-4c63-9476-33ccc31f54f8)

other extensions currently installed on chrome are here, using these on both PC and Mac:
![image](https://github.com/forgetso/search-replace/assets/106178465/195df49f-172e-479f-8967-78afcbf2916d)

Here's the zip of the webflow ecom section, where I'm struggling.
[WebflowSearchReplace.zip](https://github.com/forgetso/search-replace/files/14075905/WebflowSearchReplace.zip)

**Comment by forgetso** [comment]
Very helpful, thank you @rosasparks420. I will take a look at this later on.

**Comment by Anexis19** [comment]
@forgetso 

Monday should be great, what do you think about 13:30?

This is the Google Chrome Version 121.0.6167.86 (Official Build) (64-bit)  
Operative system: Windows 11

Thanks Chris

**Comment by forgetso** [comment]
Hi @rosasparks420, I've replicated the [issue](https://github.com/forgetso/search-replace/issues/110) you were experiencing. Version 2.0.7 will be live soon and [should fix it](https://i.imgur.com/Lcl9LGt.gif). Please let me know if it works for you!

@Anexis19 1330 tomorrow works for me. I'll email you a meeting invite if you send me your email or you can send me one to cjtaylor38@gmail.com. Thanks!

**Comment by rosasparks420** [comment]
@forgetso, angel of the earth. 🙆🏻‍♀️✨ thank you!!!!!!!!!!!!!!!!!!!!!!!!!
