### ISSUE TITLE
Unable to clear history

### ISSUE THREAD

**Issue by nebula888** [forgetso/search-replace#118]
I can't clear the history after opening any website and replacing it. When I click clear in the history option, the history disappears, but when I reopen the history, it is not deleted. The history only increases but not decreases. This problem has not occurred in previous versions. The version is 2.08 when I noticed this problem.

Please provide the following information:
- Search and Replace Version:
- Web page URL:Each website For example this Web
- Options checked (`Input fields only` etc.):none of option

**Desktop (please complete the following information):**
 - windows:edge android:kiwi
 - Version 2.0.8

**Comment by nebula888** [comment]
The browser version is the latest when I submitted the issue, I took it as this plugin version

**Comment by forgetso** [comment]
Hi @nebula888, this should now be fixed with version `2.0.9`, releasing later today.
