### ISSUE TITLE
Unable to find semicolon/special characters?

### ISSUE THREAD

**Issue by ChristopherWSmith** [forgetso/search-replace#19]
I tried searching the reviews on the Chrome Store and the other issues here, but did not see this mentioned:

I am trying to search for a phrase that includes a few special characters including ':', '-', and '>'.  It seems like adding these special characters causes the search to not find anything.  

Is there something special I have to do for it to find these special characters as part of the search string?

**Comment by forgetso** [comment]
Hi Christopher, I can replace these characters with no issues on my end. Where are you trying to replace them? If it's in a code editor then there's a good chance they are stored encoded

e.g.
```
::>>
```
is equivalent to
```
%3A%3A%3E%3E
```
https://www.urlencoder.io/

**Comment by forgetso** [comment]
Needs more info. Closing.
