### ISSUE TITLE
Add Text Switch Option

### ISSUE THREAD

**Issue by scarlet959** [forgetso/search-replace#57]
![text switch](https://github.com/forgetso/search-replace/assets/53694102/2d06f52b-3f56-4979-9665-3d605598a9b4)

Is it possible to add a text switch "option/button" to replace first text (Search for) with second text (Replace with) and second text with first text within the options.

**Comment by forgetso** [comment]
Hi @scarlet959, thanks for the feedback. I will look into adding this feature. Please leave a review if the extension helps you out!

**Comment by forgetso** [comment]
Hi @scarlet959, I have added this feature and it will be released later today. Please let me know if it helps you out!
