### ISSUE TITLE
Noob question - Search and Replace in Gutenberg

### ISSUE THREAD

**Issue by fkoomek** [forgetso/search-replace#94]
Hello!
I wasn't sure if I could post my question here but I thought I'd give it a try and you can delete it later if you want.
So, I am working on my simple script, that will search and replace certain blocks in Gutenberg. For some reason, I need to do it in batches, for example, 10 blocks at first and the next 10 blocks at second. I use a simple jQuery function but after the words are replaced, they are immediately replaced with the original values again - after I click out of the box or try to save the post.

Your plugin is the only working solution I found but I would rather have my own little solution. Would you point me please how this can be done? How does your plugin work and how can I ensure that the text is replaced and stays replaced?
Thanks for your time.

Radan

**Comment by forgetso** [comment]
Hi Radan,

I *think* Gutenberg search and replace works by bubbling up an input event:

https://github.com/forgetso/search-replace/blob/865423935d49a0134dfbe167faeb5405618c7cc3/src/searchreplace.ts#L363C5-L363C65

Give this a shot after you've made your replacements and let me know if it works.

Cheers
